# Generated by Django 4.1.1 on 2022-11-18 20:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_postmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
    ]
